BEGIN TRANSACTION;

SELECT * FROM dbo.Person;

INSERT INTO dbo.Person
VALUES ('Jake', 3400, '1340601189817');

SELECT * FROM dbo.Person;

ROLLBACK TRANSACTION;

BEGIN TRANSACTION

UPDATE dbo.Person
SET Income = 8000
WHERE Name = 'Mike';

SELECT * FROM dbo.Person;

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE

BEGIN TRANSACTION;

UPDATE dbo.Person
SET Income = 1500
WHERE Name = 'Mike';

SELECT * FROM dbo.Person;

COMMIT TRANSACTION;