SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

BEGIN TRANSACTION;

SELECT * FROM dbo.Person;

ROLLBACK TRANSACTION;

SET TRANSACTION ISOLATION LEVEL REPEATABLE READ

BEGIN TRANSACTION;

SELECT * FROM dbo.Person;
SELECT * FROM dbo.Person;

ROLLBACK TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE

BEGIN TRANSACTION;

UPDATE dbo.Person
SET Income = 1000
WHERE Name = 'Mike';

COMMIT TRANSACTION;