using Microsoft.EntityFrameworkCore.Migrations;

namespace F1Management.Infrastructure.Migrations
{
    public partial class AutoGeneratedId : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "Strategy",
                table: "RaceCars");

            migrationBuilder.AddColumn<string>(
                name: "Strategy",
                table: "Sessions",
                type: "nvarchar(max)",
                nullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "isAvailable",
                table: "PitStopCrews",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "isAvailable",
                table: "CarMechanics",
                type: "bit",
                nullable: false,
                defaultValue: false);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "Strategy",
                table: "Sessions");

            migrationBuilder.DropColumn(
                name: "isAvailable",
                table: "PitStopCrews");

            migrationBuilder.DropColumn(
                name: "isAvailable",
                table: "CarMechanics");

            migrationBuilder.AddColumn<string>(
                name: "Strategy",
                table: "RaceCars",
                type: "nvarchar(max)",
                nullable: true);
        }
    }
}
